### ISSUE TITLE
Change naming for CallMethod, SendTransaction and their responses

### ISSUE THREAD

**Issue by EsterEdelstein** [orbs-network/orbs-spec#102] opened 2018-10-08 16:22 UTC
There were several discussions and feedbacks around the naming and the response of:
- CallMethod (request & response)
-  SendTransaction (request & response) 
- GetTransactionStatus (request & response). 

We should make an educated discussion on the following: 
- **Naming**: from feedback we got, the name "call" is not clear . 
We should consider a different name that will indicate that this read only from state that is not necessarily under consensus. 
- Do we need a special receipt response just for transaction ? 
- Call method- should we change the name ? should the singer be optional ? Note that as opposed to Ethereum we in Orbs 'Call' today can not be used for simulation of state changes. 
- Should we create a separate call for deploying a contract ? if not we might be missing contract address in the response. 
 
Think about the following scenarios and what they mean:
- direct invocation of a contract method, originated with call
- direct invocation of a contract method, originated with sendTransaction
- contract invocation of a contract method, originated with call
- contract invocation of a contract method, originated with sendTransaction

**Comment by talkol** [comment] 2018-10-08 18:34
fyi @OdedWx @erankirsh @noambergIL @ronnno 
please submit your proposals here until we reach consensus

**Comment by talkol** [comment] 2018-10-08 19:58
I propose to make the following changes:

### 1. Terminology: Transaction vs. Query

* `Transaction` - action under consensus, can modify state, written to the blockchain, has a **receipt**
* `Query` - action without consensus, read only, not stored on the blockchain log, has a **result**

### 2. New names for our basic Public Apis

* `SendTransaction` stays with same name
* `CallMethod` rename to `RunQuery`
* `GetTransactionStatus` stays with same name

### 3. New protos for Transaction

Summary of changes (regarding the old terminology):
* Don't use the term `Transaction` with `CallMethod`
* Move the `signer` from  `Transaction` to `SignedTransaction`

Therefore the new protos become:

```proto
message ContractCall { // this used to be called Transaction
    primitives.protocol_version protocol_version = 1;
    primitives.virtual_chain_id virtual_chain_id = 2;
    primitives.timestamp_nano timestamp = 3;
    primitives.contract_name contract_name = 4;
    primitives.method_name method_name = 5;
    bytes input_argument_array = 6;
}

message Transaction { // this used to be called SignedTransaction
    ContractCall call = 1;
    protocol.Signer signer = 2; // this used to be inside ContractCall (previously Transaction)
    bytes signature = 3;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/transactions.proto)

### 4. New protos for the results

```proto
message TransactionReceipt {
    primitives.sha256 txhash = 1;
    ContractCallResult result = 2; // used to be flat inside the receipt
}

message ContractCallResult { // used to be duplicated in transaction and query responses
    protocol.ExecutionResult execution_result = 1;
    bytes output_argument_array = 2;
}

message RequestResult { // used to be duplicated in all responses
    protocol.RequestStatus request_status = 1;
    primitives.block_height block_height = 2;
    primitives.timestamp_nano block_timestamp = 3;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/transactions.proto)

### 5. New protos for the client requests

Summary of changes (regarding the old terminology):
* Merge `SendTransactionResponse` and `GetTransactionStatusResponse` since they're identical
* All 3 responses contain `request_status`, `block_height`, `block_timestamp` so extract this into a new message that can be used in all 3 to avoid duplication
* Extract `execution_result`, `output_argument_array` into a new message that can be used both for transaction results and query results
* Allow `CallMethod` to be signed - the signature should be optional, both the `signer` and `signature` fields can be empty and the query is still valid. I ultimately think it's a good idea to allow signing queries to allow gateways to fight spam better by providing them with proofs of sender.

Therefore the new protos become:

```proto
message SendTransactionRequest {
    protocol.Transaction transaction = 1; // used to be SignedTransaction
} // the response for this request is TransactionResponse

message GetTransactionStatusRequest {
    primitives.timestamp_nano transaction_timestamp = 1;
    primitives.sha256 txhash = 2;
} // the response for this request is TransactionResponse

message TransactionResponse { // used to be SendTransactionResponse
    RequestResult request_result = 1;
    protocol.TransactionStatus transaction_status = 2;
    protocol.TransactionReceipt transaction_receipt = 3;
}

message RunQueryRequest {
    protocol.ContractCall query = 1;
    protocol.Signer optional_signer = 2;
    bytes optional_signature = 3;
} // the response for this request is QueryResponse

message QueryResponse {
    RequestResult request_result = 1;
    ContractCallResult query_result = 2;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/client/requests.proto)

**Comment by OdedWx** [comment] 2018-10-09 07:03
Few points to consider following our discussion:

1. signer and signature in query
There is a value in providing the signer even if the query isn't signed. For example get_my_ballance, I don't see a problem of using another client identity when querying

2. Combining the receipt data structure and the query response is problematic for forward compatibility, for example if we add logs, we may want to add them to the query response but not to the receipt

3. The nesting in the receipt increases the receipt size, consider to flat.

4. Partially related:
a. Should add version to the transaction and query responses. (part of the versioning issue)
b. Consider to remove the Signer message and use a flat primitive (part of the addressing issue)

**Comment by talkol** [comment] 2018-10-09 07:06
After a short discussion with Oded, here's another proposal that is more geared towards performance and future compatibility:

### 1. Terminology: Transaction vs. Query

* `Transaction` - action under consensus, can modify state, written to the blockchain, has a **receipt**
* `Query` - action without consensus, read only, not stored on the blockchain log, has a **result**

### 2. New names for our basic Public Apis

* `SendTransaction` stays with same name
* `CallMethod` rename to `RunQuery`
* `GetTransactionStatus` stays with same name

### 3. New protos for Transaction

Summary of changes (regarding the old terminology):
* Don't use the term `Transaction` with `CallMethod`
* Move the `signer` from  `Transaction` to `SignedTransaction`
* Create `Query` which is a duplicate of `Transaction` (for future compatibility in case their fields end up different)

Therefore the new protos become:

```proto
message Transaction {
    primitives.protocol_version protocol_version = 1;
    primitives.virtual_chain_id virtual_chain_id = 2;
    primitives.timestamp_nano timestamp = 3;
    primitives.contract_name contract_name = 4;
    primitives.method_name method_name = 5;
    bytes input_argument_array = 6;
}

message SignedTransaction {
    Transaction transaction = 1;
    protocol.Signer signer = 2; // this used to be inside Transaction
    bytes signature = 3;
}

message Query {
    primitives.protocol_version protocol_version = 1;
    primitives.virtual_chain_id virtual_chain_id = 2;
    primitives.timestamp_nano timestamp = 3;
    primitives.contract_name contract_name = 4;
    primitives.method_name method_name = 5;
    bytes input_argument_array = 6;
}

message SignedQuery {
    Query query = 1;
    protocol.Signer signer = 2; // this used to be inside Transaction
    bytes signature = 3;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/transactions.proto)

### 4. New protos for the results

Summary of changes (regarding the old terminology):
* Create `QueryResult` which is a duplicate of `TransactionReceipt` (for future compatibility in case their fields end up different)

Therefore the new protos become:

```proto
message TransactionReceipt {
    primitives.sha256 txhash = 1;
    protocol.ExecutionResult execution_result = 2;
    bytes output_argument_array = 3;
}

message QueryResult {
    protocol.ExecutionResult execution_result = 1;
    bytes output_argument_array = 2;
}

message RequestResult { // used to be duplicated in all responses
    protocol.RequestStatus request_status = 1;
    primitives.block_height block_height = 2;
    primitives.timestamp_nano block_timestamp = 3;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/transactions.proto)

### 5. New protos for the client requests

Summary of changes (regarding the old terminology):
* All 3 responses contain `request_status`, `block_height`, `block_timestamp` so extract this into a new message that can be used in all 3 to avoid duplication
* Allow `CallMethod` to be signed - the signature should be optional, both the `signer` and `signature` fields can be empty and the query is still valid. I ultimately think it's a good idea to allow signing queries to allow gateways to fight spam better by providing them with proofs of sender.

Therefore the new protos become:

```proto
message SendTransactionRequest {
    protocol.SignedTransaction signed_transaction = 1;
}

message SendTransactionResponse {
    RequestResult request_result = 1;
    protocol.TransactionStatus transaction_status = 2;
    protocol.TransactionReceipt transaction_receipt = 3;
}

message GetTransactionStatusRequest {
    primitives.timestamp_nano transaction_timestamp = 1;
    primitives.sha256 txhash = 2;
}

message GetTransactionStatusResponse {
    RequestResult request_result = 1;
    protocol.TransactionStatus transaction_status = 2;
    protocol.TransactionReceipt transaction_receipt = 3;
}

message RunQueryRequest {
    protocol.SignedQuery signed_query = 1;
}

message RunQueryResponse {
    RequestResult request_result = 1;
    protocol.QueryResult query_result = 2;
}
```
* Note: For the existing protos look [here](https://github.com/orbs-network/orbs-spec/blob/bfef7236553d4c4150ace26754e1b83181e3307e/interfaces/protocol/client/requests.proto)

**Comment by talkol** [comment] 2018-10-09 07:08
Between my two proposals, I currently vote for the second

**Comment by noambergIL** [comment] 2018-10-09 07:37
We were told/asked to add a GetMerkleProof Function ... it might be early as we still don't have the merkle protos ... but let's at least see that it "fits" this new proposal

**Comment by noambergIL** [comment] 2018-10-09 09:15
can i ask to have only a top level copy ? i would like to avoid having this kind of code:
	var receiptForClient *protocol.TransactionReceiptBuilder = nil

	_if receipt := transactionOutput.transactionReceipt; receipt != nil {
		receiptForClient = &protocol.TransactionReceiptBuilder{
			Txhash:              receipt.Txhash(),
			ExecutionResult:     receipt.ExecutionResult(),
			OutputArgumentArray: receipt.OutputArgumentArray(),
		}
	}_

	response := &client.GetTransactionStatusResponseBuilder{
		RequestStatus:      translateTxStatusToResponseCode(transactionOutput.transactionStatus),
		TransactionReceipt: receiptForClient,
		TransactionStatus:  transactionOutput.transactionStatus,
		BlockHeight:        transactionOutput.blockHeight,
		BlockTimestamp:     transactionOutput.blockTimestamp,
	}

	return &services.GetTransactionStatusOutput{ClientResponse: response.Build()}
}

**Closed as completed** 2019-01-08 15:44 UTC
Labels: discussion
